### PR TITLE
[FIX] stock_batch_picking_ux: For pickings to remove we don't check lots.

### PR DESCRIPTION
**Pull request by nicomacr**
### Ticket 45582

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/303).

**Review by jcadhoc — APPROVED** [review]

**Comment by nicomacr** [comment]
delegate jcadhoc

**Comment by nicomacr** [comment]
roboadhoc delegate jcadhoc

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Staging failed: ci/oba_with_tests on d5028e1a964f00cca68ca1f9829ecf1d73a47dfd (view more at http://runbot.adhoc.com.ar/runbot/build/6359)

**Pull request merged**
