### PR TITLE
[ADD]sale_order_type_invoice_policy_invoice_link:new module

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/584).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#591

**Pull request closed without merging**
