### PR TITLE
[FIX] stock_voucher: adjustments to validate more than one picking

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/340).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@augusto-weiss, you may want to rebuild or fix this PR as it has failed CI.

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti. This PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
