### PR TITLE
[MOV] [IMP]  Replenishment: move toggle from stock_orderpoint_manual_update to stock_ux

### PR DESCRIPTION
**Pull request by ced-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/557).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#558

**Pull request closed without merging**
