### PR TITLE
[FW][ADD] stock_orderpoint_manual_update: new_module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#427

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/444).

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request merged**
