### PR TITLE
[FIX] stock_batch_picking_ux: For pickings to remove we don't check l…

### PR DESCRIPTION
**Pull request by jjscarafia**
…ots.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/304).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
