### PR TITLE
[FIX] stock_orderpoint_manual_update: fix filter by locations

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/455).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#456

**Pull request closed without merging**
