### PR TITLE
[FIX] stock_batch_picking_ux: transfer voucher number from batch to pickings

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/436).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#438

**Pull request closed without merging**
