### PR TITLE
[FIX] stock_ux: deliveryslip fix

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/389).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @mav-adhoc. I'm afraid I can't do that.

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
