### PR TITLE
[FIX] stock_ux: remove onchange method that Odoo removed

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by augusto-weiss** [comment]
@fw-bot-adhoc ignore

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/324).

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Comment by nicomacr** [comment]
p=0

**Pull request closed without merging**
