### PR TITLE
[FIX]stock_request_ux: OCA added this fields

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/493).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#504

**Pull request closed without merging**
