### PR TITLE
[MIG] stock_lot_information: Migration to 15.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/335).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
