### PR TITLE
[REM] stock_picking_partner_editable

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/368).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @augusto-weiss: draft PRs can not be approved.

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
