### PR TITLE
[REM] stock_picking_ean128_report

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/328).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests override=ci/argentina-ee

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Pull request closed without merging**
