### PR TITLE
[FW][FIX] stock_ux: cancel remaining error

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#351

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/352).

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jok-adhoc: I must know your email before you can review PRs. Please contact an administrator.

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
