### PR TITLE
[MIG] delivery_ux: Migration to 17.0

### PR DESCRIPTION
**Pull request by mem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/478).

**Review by zaoral — CHANGES_REQUESTED** [review]
clean up the imports not used in models/delivery_carrier

**Comment by pablohmontenegro** [comment]
@mem-adhoc rebase pr please. Thanks!

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by mem-adhoc** [comment]
@pablohmontenegro Hello Pablo, I made a rebase again because the runbot error was still red, now if the tests are all green you can give r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Pull request merged**
