### PR TITLE
[MIG] stock_ux: Migration to 16.0

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/353).

**Review by maq-adhoc — DISMISSED** [review]

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
