### PR TITLE
[FIX] stock_ux: cancel remaining error

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/351).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#352

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#352

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#352

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#352

**Pull request closed without merging**
