### PR TITLE
[FW][ADD]stock_batch_picking:solapa transferencias

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#417

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/418).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
