### PR TITLE
[ADD]stock_ux: re-add chatter in stock.warehouse.orderpoint

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/449).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by bruno-zanotti** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc unable to stage: commits with multiple parents (3b753268ceaaf96638bf39862994cd8409082d4e) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc unable to stage: commits with multiple parents (3b753268ceaaf96638bf39862994cd8409082d4e) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#458

**Pull request closed without merging**
