### PR TITLE
[MIG] stock_picking_labels: Migration to 16.0

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/349).

**Comment by maq-adhoc** [comment]
@roboadhoc r+ override=ci/oba_without_tests p=0

**Comment by roboadhoc** [comment]
@maq-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc: you are not allowed to override this status.

**Comment by matiasperalta1** [comment]
@roboadhoc r+ override=ci/oba_without_tests p=0

**Comment by roboadhoc** [comment]
@augusto-weiss @maq-adhoc we apparently missed an update to this PR and tried to stage it in a state which might not have been approved. PR has been updated to 8980e4dd5f101dfc8cab40b1821c93d59c80dbe2, please check and approve or re-approve.

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: you are not allowed to override this status.

**Pull request closed without merging**
