### PR TITLE
[ADD]stock_ux:quick wins

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/459).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#468

**Pull request closed without merging**
