### PR TITLE
[FW][FIX] stock_request_ux: permitir ingresar a pedidos de existencia

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 35651
Permitir ingresar a pedidos de existencia a usuarios que no tienen permiso de Administración/Settings

Forward-Port-Of: ingadhoc/stock#451

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/454).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 17.0 and is the last of the forward-port chain containing:
* ingadhoc/stock#453

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
