### PR TITLE
[FIX] stock_request_ux: correct partner in picking

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/488).

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @ced-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @ced-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#528

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @ced-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#528

**Pull request closed without merging**
