### PR TITLE
[ADD]stock_batch_picking:solapa transferencias

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/417).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#418

**Pull request closed without merging**
