### PR TITLE
[FIX] stock_ux: rename context keys

### PR DESCRIPTION
**Pull request by bruno-zanotti**
This is to avoid context errors in other odoo actions.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/326).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti. You can't review+.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
