### PR TITLE
[ADD] stock_ux: zpl and pdf report, change of repository

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/390).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#398

**Pull request closed without merging**
