### PR TITLE
[FIX] stock_ux: expiration_date in lot

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/421).

**Comment by ALopez-Adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#425

**Pull request closed without merging**
