### PR TITLE
[MIG] stock_request_ux: Migration to 16.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/360).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti you may want to rebuild or fix this PR as it has failed CI.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
