### PR TITLE
[ADD] stock_ux:orderpoint-qty_forecast_stored field

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/429).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#435

**Pull request closed without merging**
