### PR TITLE
[MIG] stock_voucher and delivery_ux

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/307).

**Pull request merged**
