### PR TITLE
[FIX] stock_ux: migration error

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/369).

**Comment by JoelZilli** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@JoelZilli you may want to rebuild or fix this PR as it has failed CI.

**Comment by JoelZilli** [comment]
@roboadhoc r+

**Pull request closed without merging**
