### PR TITLE
[FW][ADD] stock_ux: stock.move.line views

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#406

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/409).

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @nicomacr this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @nicomacr this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request merged**
