### PR TITLE
[FIX] stock_ux: duplicated field product_uom_id in tree view

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/469).

**Comment by jcadhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by jcadhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: you are not allowed to override this status.

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc:
- this PR is already reviewed, reviewing it again is useless.
- you are not allowed to override this status.

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#470

**Pull request closed without merging**
