### PR TITLE
[IMP] stock_voucher: Change in the file name of the Delivery Slip report

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/370).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/stock#374

**Pull request closed without merging**
