### PR TITLE
[ADD] stock_ux: Traceability button in reposition

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/457).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#464

**Pull request closed without merging**
