### PR TITLE
[REF] stock_ux: replace method message_post_with_template with a new one

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/472).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
