### PR TITLE
[FW][REM] _manual_update: eliminate method because odoo incorporates it

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#578

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/582).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @jjscarafia this PR targets 18.0 and is the last of the forward-port chain containing:
* ingadhoc/stock#581

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @jjscarafia this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
