### PR TITLE
[ADD]stock_move:comments of flor task 34343

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/499).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @mav-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by mav-adhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
