### PR TITLE
[FIX] stock_ux: new origin_description field to show in Delivery Slip

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/377).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@vib-adhoc @Bruno-Zanotti linked pull request(s) ingadhoc/purchase#170 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
