### PR TITLE
[FW][FIX] stock_ux: duplicated field product_uom_id in tree view

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#469

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/470).

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc cherrypicking of pull request ingadhoc/stock#469 failed.

stdout:
```
Auto-merging stock_ux/views/stock_move_line_views.xml
CONFLICT (content): Merge conflict in stock_ux/views/stock_move_line_views.xml
Auto-merging stock_ux/__manifest__.py
CONFLICT (content): Merge conflict in stock_ux/__manifest__.py

```

stderr:
```
19:06:15.903282 git.c:444               trace: built-in: git cherry-pick e924fd3d164497deb4001f1bb45c214e0b37f1b5
error: could not apply e924fd3d... [FIX] stock_ux: duplicated field product_uom_id in tree view
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
