### PR TITLE
[FIX] stock_ux: transfer of functionality to sale_stock_ux

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/385).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@ALopez-Adhoc @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by ALopez-Adhoc** [comment]
@roboadhoc merge

**Comment by roboadhoc** [comment]
I'm sorry, @ALopez-Adhoc: you can't method=merge.

**Comment by ALopez-Adhoc** [comment]
@roboadhoc rebase-merge

**Comment by roboadhoc** [comment]
I'm sorry, @ALopez-Adhoc: you can't method=rebase-merge.

**Comment by ALopez-Adhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
I'm sorry, @ALopez-Adhoc: you can't method=rebase-ff.

**Comment by jcadhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
