### PR TITLE
[FW][IMP] stock_ux, stock_orderpoint_manual_update: replenishment rules improvements

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#467

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/474).

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti cherrypicking of pull request ingadhoc/stock#467 failed.

* 259ce3908cee065f42290bbc019ee6434bf10070
* f621bc490be45c4916ae38830614f58a64726210 <- on this commit
* 1ea690cb1935962bd88a0977e1d78a949746a926
* bf792d2fc7a14ece0ace9fe64c89a0bae1bf6187
* 626ce0367da36c66f31ad17b5d529fa63d2b2470

stderr:
```
21:54:32.313197 git.c:444               trace: built-in: git cherry-pick f621bc490be45c4916ae38830614f58a64726210
error: Cherry-picking is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti linked pull request(s) ingadhoc/purchase#196 not ready. Linked PRs are not staged until all of them are ready.

**Pull request closed without merging**
