### PR TITLE
[IMP] stock_ux: show location and warehouse filters on all views

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/448).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia @jcadhoc linked pull request(s) ingadhoc/purchase#180, ingadhoc/sale#781 not ready. Linked PRs are not staged until all of them are ready.

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/stock#450

**Pull request closed without merging**
