### PR TITLE
[FIX] stock_ux: Change observation to HTMl and fix button in product form view.

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/stock/pull/329).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Pull request closed without merging**
