### PR TITLE
[FW][MOV] [IMP]  Replenishment: move toggle from stock_orderpoint_manual_update to stock_ux

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/stock#557

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/stock/pull/558).

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
